apiVersion: v1
kind: Service
metadata:
  name: aws-app-mesh-inject
  namespace: appmesh-system
  labels:
    app: aws-app-mesh-inject
spec:
  ports:
    - name: webhook
      port: 443
      targetPort: 8080
  selector:
    app: aws-app-mesh-inject