apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: appmesh-system
  labels:
    name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      protocol: TCP
      port: 9090
