apiVersion: v1
kind: Service
metadata:
  name: backend-canary
  namespace: test
  labels:
    app: backend-canary
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 9898
    protocol: TCP
    targetPort: http
