apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress
  template:
    metadata:
      labels:
        app: ingress
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9901"
    spec:
      containers:
        - name: nginx
          image: nginx:1.15
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 128Mi
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: config
        - name: envoy
          image: 111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.8.0.2-beta
          securityContext:
            runAsUser: 1337
          env:
            - name: "APPMESH_VIRTUAL_NODE_NAME"
              value: "mesh/global/virtualNode/ingress"
            - name: "ENVOY_LOG_LEVEL"
              value: "debug"
            - name: "AWS_REGION"
              value: "us-west-2"
      initContainers:
        - name: proxyinit
          image: 111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-proxy-route-manager:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: "APPMESH_START_ENABLED"
              value: "1"
            - name: "APPMESH_IGNORE_UID"
              value: "1337"
            - name: "APPMESH_ENVOY_INGRESS_PORT"
              value: "15000"
            - name: "APPMESH_ENVOY_EGRESS_PORT"
              value: "15001"
            - name: "APPMESH_APP_PORTS"
              value: "80"
            - name: "APPMESH_EGRESS_IGNORED_IP"
              value: "169.254.169.254"
      volumes:
        - name: config
          configMap:
            name: ingress-config
