apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-mesh-controller
  namespace: appmesh-system
  labels:
    app: app-mesh-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-mesh-controller
  template:
    metadata:
      labels:
        app: app-mesh-controller
    spec:
      serviceAccountName: app-mesh-sa
      containers:
        - name: app-mesh-controller
          image: stefanprodan/app-mesh-controller:0.0.1-alpha.1
          ports:
            - containerPort: 10555
