apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-mesh-sa
  namespace: appmesh-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: app-mesh-controller
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]
  - apiGroups: ["appmesh.k8s.aws"]
    resources: ["meshes", "virtualnodes", "virtualservices", "meshes/status", "virtualnodes/status", "virtualservices/status"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: app-mesh-controller-binding
subjects:
  - kind: ServiceAccount
    name: app-mesh-sa
    namespace: appmesh-system
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: app-mesh-controller
  apiGroup: ""
